language: php

sudo: false

matrix:
  include:
    - php: 7.1
      env: COMPOSER_FLAGS='--prefer-lowest --prefer-stable'
    - php: 7.2
    - php: 7.3
    - php: 7.4
    - php: nightly
  fast_finish: true

cache:
  directories:
    - $HOME/.composer/cache/files
    - $HOME/symfony-bridge/.phpunit

env:
  global:
    - SYMFONY_PHPUNIT_DIR="$HOME/symfony-bridge/.phpunit"
    - COMPOSER_FLAGS=''
    
before_install:
  - ([[ $TRAVIS_PHP_VERSION = nightly ]] && composer config platform.php 7.4.99 || true)
  - composer validate

install:
  - composer require --no-update composer/composer:^1.0.2
  - composer update $COMPOSER_FLAGS

script:
  - ./vendor/bin/simple-phpunit
  - composer self-update --snapshot
  - composer require --no-update composer/composer:^2
  - composer update $COMPOSER_FLAGS
  - ./vendor/bin/simple-phpunit
  - find src/ -name '*.php' | xargs -n1 php -l
